# Discussed at https://travis-ci.community/t/python-support-on-windows/241/18
#
language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.7 on Xenial Linux"
      script:
        - pip3 install -r external/requirements.txt
        - pyinstaller -F external/configure_panorama.py
        - cp dist/configure_panorama modules/panorama/
        - zip -ur bundle-linux.zip variables.tf README.md modules main.tf external
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
      deploy:
        - provider: releases
          api_key: $api_token
          file:
            - "bundle-linux.zip"
          skip_cleanup: true
          on:
            tags: true

    - name: "Python 3.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      install:
        - pip3 install -r external/requirements.txt
      before_install:
        - choco install python  # this install takes at least 1 min 30 sec
        - choco install zip  # this install takes at least 1 min 30 sec
      script:
        - pyinstaller -F external/configure_panorama.py
        - cp dist/configure_panorama.exe modules/panorama/
        - zip -ur bundle-windows.zip variables.tf README.md modules main.tf external
      deploy:
        - provider: releases
          api_key: $api_token
          file:
            - "bundle-windows.zip"
          skip_cleanup: true
          on:
            tags: true

    - name: "Python on macOS"
      os: osx
      osx_image: xcode12  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      script:
        - pip3 install -r external/requirements.txt
        - pyinstaller -F external/configure_panorama.py
        - cp dist/configure_panorama modules/panorama/
        - zip -ur bundle-linux.zip variables.tf README.md modules main.tf external
      deploy:
        - provider: releases
          api_key: $api_token
          file:
            - "bundle-macOS.zip"
          skip_cleanup: true
          on:
            tags: true


notifications:
  email: false